apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1reimb-dep
  labels:
    app: api1reimb-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api1reimb-api
  template:
    metadata:
      labels:
        app: api1reimb-api
    spec:
      containers:
        - image: jschuwan/api1
          imagePullPolicy: Always
          name: api1reimb-api
          ports:
            - containerPort: 8080
            
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api1reimb-api
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
