
pr:
  condition: ${{ parameters.runAnalysis }}
  branches:
    include:
    - master
  paths:
    include:
    - folder/file.yml
    - another

parameters:
- name: runAnalysis
  displayName: Run tests & SonarQube?
  type: boolean
  default: false

# beforeafter
jobs:
- template: beforeafter.yml
  parameters:
    jobs:
    - job: A
      steps:
      - script: echo This will get sandwiched between SetupMyBuildTools and PublishMyTelemetry.
    - job: B
      steps:
      - script: echo So will this!
      
 # specialtool
 jobs:
- template: specialtool.yml
  parameters:
    jobs:
    - job: A
      steps:
      - script: echo This job depends on SomeSpecialTool, even though it's not explicitly shown here.
    - job: B
      dependsOn:
      - A
      steps:
      - script: echo This job depends on both Job A and on SomeSpecialTool.
      
  # File: azure-pipelines.yml
      steps:
      - template: conditional.yml
        parameters:
          toolset: dotnet
      - template: sconditional.yml
        parameters:
           debug: true
